### ISSUE TITLE
[Question] Way to output theme from another builder?

### ISSUE THREAD

**Issue by ghost** [golf1052/base16-vscode#5]
I use flavours, and would like to set the theme in flavours, and have it applied near everywhere I can at once. What triggers would I use to activate your extention from flavours, or use the template provided on this repo?

**Comment by Haze-sh** [comment]
I was stuck on the same issue till I've found a solution (maybe there's a better solution though). Edit the package.json file on the extension's directory (./vscode/extensions/golf1052.base16-generator-1.15.0) and under "themes" change the label and path to the name and path of the file you want to edit by your injector (which is flavours in this case). The path of the file should be in the themes directory inside the extension's directory.

**Comment by golf1052** [comment]
I'm not sure what "flavours" is.

**Comment by Haze-sh** [comment]
It is a theme generator and injector software: [flavours](https://github.com/Misterio77/flavours).

**Comment by golf1052** [comment]
After setting up Manjaro and trying flavours out while following [this tutorial](https://www.youtube.com/watch?v=Hjq15PVY0Tk) it seems like @Haze-sh solution would work. Another solution is using a custom sub-template [I've created one here](https://gist.github.com/golf1052/515f3904b89552bbac53f74c9f7cc56f) and then adding start and end lines in your user settings.json file.
